dist: bionic
language: node_js
node_js:
  - 15

notifications:
  email:
    on_success: never
    on_failure: always

git:
  quiet: true

services:
  - xvfb

addons:
  apt:
    # Dependencies pulled from https://playwright.dev/docs/ci/#travis-ci
    packages:
      # These are required to run webkit
      - libwoff1
      - libopus0
      - libwebp6
      - libwebpdemux2
      - libenchant1c2a
      - libgudev-1.0-0
      - libsecret-1-0
      - libhyphen0
      - libgdk-pixbuf2.0-0
      - libegl1
      - libgles2
      - libevent-2.1-6
      - libnotify4
      - libxslt1.1
      - libvpx5
      # gstreamer and plugins to support video playback in WebKit.
      - gstreamer1.0-gl
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      # This is required to run chromium
      - libgbm1
      # this is needed for running headed tests
      - xvfb

# Allow headed tests: pulled from https://playwright.dev/docs/ci/#travis-ci
before_install:
  # Enable user namespace cloning
  - "sudo sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"

install:
  - npm install
  - npx playwright install
