export let Tags = {
  Budgeting: "budgeting",
  Business: "business",
  BusinessDevelopment: "business development",
  BusinessStrategy: "business strategy",
  CloudComputing: "cloud computing",
  DevTools: "devtools",
  Docker: "docker",
  Entrepreneurship: "entrepreneurship",
  Erp: "erp",
  FinancialIndependence: "financial independence",
  Flask: "flask",
  Investments: "investments",
  Leadership: "leadership",
  Nginx: "nginx",
  OpenSource: "open source",
  Odoo: "odoo",
  Productivity: "productivity",
  ProjectManagement: "project management",
  Python: "python",
  Refactoring: "refactoring",
  SaaS: "software as a service",
  SmallBusiness: "small business",
  Software: "software",
  SoftwareCraftsmanship: "software craftsmanship",
  SoftwareTesting: "software testing",
  Stripe: "stripe",
  UnitTesting: "unit testing",
  WebDevelopment: "web development",
}
